esudo: false
branches:
  only:
  - develop
language: node_js
node_js:
- '12'
before_install:
- 'pwd && ls -als'
- npm --global install npm@latest
#- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
#- 'export PATH="$HOME/.yarn/bin:$PATH"'
#cache:
#  yarn: true
install:
- 'pwd && ls -als'
before_script:
- 'pwd && ls -als'
#- 'yarn --version'
#- 'yarn install --ignore-engines'
- 'node --version'
- 'npm --version'
- 'npm ci'
script:
- npm run build
#- 'npm run now'
#- 'npx now alias --token=$NOW_TOKEN $(npx now ./now --no-clipboard --token=$NOW_TOKEN --public) readium2.now.sh'
after_success:
- 'pwd && ls -als'
- 'ls dist'
after_failure:
- 'pwd && ls -als'
